services:
  - type: web
    name: pulse-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
